"""Default config-field comments used by frontend help popovers.

Generated from examples/config_template.json::__comments.
"""

DEFAULT_CONFIG_COMMENTS = {
  "best_params_files": "Mapping from model key to an external best-params file path.",
  "binary_resp_nme": "Optional binary response column used by some classification workflows.",
  "bo_sample_limit": "Optional maximum rows used during BayesOpt tuning (null means no cap).",
  "bootstrap": "Bootstrap confidence-interval options object.",
  "bootstrap.ci": "Confidence level (for example 0.95).",
  "bootstrap.enable": "Enable bootstrap confidence interval estimation.",
  "bootstrap.metrics": "Metric names to evaluate with bootstrap.",
  "bootstrap.n_samples": "Number of bootstrap resamples.",
  "bootstrap.seed": "Random seed for bootstrap resampling.",
  "build_oht": "If true, build one-hot transformed features for models that need OHT input.",
  "cache_predictions": "If true, persist train/test predictions after training.",
  "calibration": "Calibration options object.",
  "calibration.enable": "Enable probability calibration for classification outputs.",
  "calibration.max_rows": "Maximum rows used for calibration fit.",
  "calibration.method": "Calibration method. Typical values: sigmoid, isotonic.",
  "calibration.seed": "Random seed for calibration sampling.",
  "categorical_features": "Feature columns treated as categorical.",
  "classification_label_threshold": "Threshold in [0, 1] used when converting classification scores to labels.",
  "classification_plot_prediction": "Classification value used for plotting. Allowed: score, label.",
  "classification_predict_api": "Classification prediction API mode. Allowed: label, score.",
  "classification_prediction_outputs": "Classification outputs to store. Allowed: score, both.",
  "cv_group_col": "Grouping column used by group/grouped CV strategies.",
  "cv_splits": "Number of cross-validation folds.",
  "cv_strategy": "Cross-validation strategy. Allowed: random, group, grouped, time, timeseries, temporal, stratified.",
  "cv_time_ascending": "Sort direction for time-based CV.",
  "cv_time_col": "Time column used by time/timeseries/temporal CV strategies.",
  "data_dir": "Directory that contains input datasets.",
  "data_fingerprint_max_bytes": "Maximum bytes read when computing data fingerprint/hash.",
  "data_format": "Dataset file format. Allowed: auto, csv, parquet, feather.",
  "data_path_template": "Dataset filename template. Supports placeholders like {model_name} and {ext}.",
  "dataloader_multiprocessing_context": "Explicit DataLoader multiprocessing context. Allowed: fork, spawn, forkserver.",
  "dataloader_workers": "DataLoader worker-process count (null/absent = auto by profile/platform).",
  "ddp_min_rows": "Minimum row count required before enabling DDP optimization path.",
  "distribution": "Optional distribution override. Common values: auto, tweedie, poisson, gamma, gaussian, laplace, bernoulli (classification).",
  "dtype_map": "Optional dtype mapping (inline dict or path to a JSON file) used when reading input data.",
  "env": "Environment variable overrides injected before running training.",
  "env.BAYESOPT_DATALOADER_MP_CONTEXT": "DataLoader multiprocessing context override. Allowed: fork, spawn, forkserver.",
  "env.BAYESOPT_DDP_ALLOW_WORKERS_IN_MEMORY_SAVING": "Allow non-zero DataLoader workers in memory_saving profile under DDP. Allowed: 0/1.",
  "env.BAYESOPT_DDP_BARRIER_DEBUG": "Enable verbose DDP barrier logging. Allowed: 0/1.",
  "env.BAYESOPT_DDP_BARRIER_TIMEOUT": "DDP barrier timeout (seconds).",
  "env.BAYESOPT_DDP_META_READ_TIMEOUT_SECONDS": "Timeout for DDP metadata reads (seconds).",
  "env.BAYESOPT_DDP_TIMEOUT_SECONDS": "DDP process-group initialization timeout (seconds).",
  "env.BAYESOPT_GNN_MPS_DENSE_MAX_NODES": "Maximum node count before avoiding dense MPS GNN computation.",
  "env.BAYESOPT_RESOURCE_PROFILE": "Resource profile. Allowed: auto, throughput, memory_saving, cpu, mps, cuda (cpu/mps/cuda are treated as auto).",
  "env.NCCL_ASYNC_ERROR_HANDLING": "Enable NCCL async error handling. Allowed: 0/1.",
  "env.NCCL_DEBUG": "NCCL debug level (for Linux NCCL backend). Typical values: WARN, INFO.",
  "env.OMP_NUM_THREADS": "OMP_NUM_THREADS value (controls OpenMP CPU threads).",
  "env.OPENBLAS_NUM_THREADS": "OPENBLAS_NUM_THREADS value (controls OpenBLAS CPU threads).",
  "env.PYTORCH_ENABLE_MPS_FALLBACK": "Enable CPU fallback for unsupported MPS ops. Allowed: 0/1.",
  "env.INS_PRICING_ALLOW_LEGACY_TORCH_LOAD": "Allow trusted torch1.x fallback when weights_only load is unavailable. Allowed: 0/1.",
  "env.TORCHDYNAMO_DISABLE": "Disable TorchDynamo. Allowed: 0/1.",
  "env.TORCHDYNAMO_SUPPRESS_ERRORS": "Suppress TorchDynamo errors and fallback to eager mode. Allowed: 0/1.",
  "env.TORCHINDUCTOR_DISABLE": "Disable TorchInductor backend. Allowed: 0/1.",
  "env.TORCH_COMPILE_DISABLE": "Disable torch.compile. Allowed: 0/1.",
  "env.TORCH_DISABLE_DYNAMO": "Compatibility switch to disable Dynamo. Allowed: 0/1.",
  "env.TORCH_DISTRIBUTED_DEBUG": "PyTorch distributed debug level. Typical values: OFF, INFO, DETAIL.",
  "epochs": "Training epochs for neural models (FT/ResNet/GNN).",
  "explain": "Explainability workflow configuration object.",
  "explain.integrated_gradients": "Integrated-gradients options object.",
  "explain.integrated_gradients.baseline": "Generic baseline value/tensor for integrated gradients.",
  "explain.integrated_gradients.baseline_geo": "Geo-input baseline for FT integrated gradients.",
  "explain.integrated_gradients.baseline_num": "Numeric-input baseline for FT integrated gradients.",
  "explain.integrated_gradients.batch_size": "Batch size used during integrated-gradients computation.",
  "explain.integrated_gradients.save_values": "If true, save raw attribution arrays from integrated gradients.",
  "explain.integrated_gradients.steps": "Number of path-integration steps.",
  "explain.integrated_gradients.target": "Optional target index/class for integrated gradients.",
  "explain.methods": "Explain methods to run. Allowed: permutation, shap, integrated_gradients.",
  "explain.model_dir": "Optional override for directory that stores trained model artifacts.",
  "explain.model_keys": "Model keys to explain. Common keys: xgb, resn, ft, glm, gnn, all.",
  "explain.on_train": "If true, run explainability on train split; otherwise use holdout/test split.",
  "explain.permutation": "Permutation-importance options object.",
  "explain.permutation.max_rows": "Maximum sampled rows used for permutation importance.",
  "explain.permutation.metric": "Metric used for permutation importance. 'auto' resolves from task type.",
  "explain.permutation.n_repeats": "Number of random shuffles per feature in permutation importance.",
  "explain.permutation.random_state": "Random seed for permutation importance.",
  "explain.result_dir": "Optional override for directory that stores intermediate results used by explain workflow.",
  "explain.save_dir": "Output directory for explain artifacts.",
  "explain.shap": "SHAP options object.",
  "explain.shap.n_background": "Number of background rows used by SHAP explainer.",
  "explain.shap.n_samples": "Number of rows to explain with SHAP.",
  "explain.shap.save_values": "If true, save raw SHAP value arrays in addition to aggregated outputs.",
  "explain.train_path": "Optional explicit training dataset path for explain workflow.",
  "explain.validation_path": "Optional explicit validation dataset path for explain workflow.",
  "feature_list": "Feature columns used for training/inference.",
  "final_ensemble": "If true, run final ensemble prediction using multiple folds/models.",
  "final_ensemble_k": "Number of ensemble members/folds used when final_ensemble=true.",
  "final_refit": "If true, refit final model on full training data after tuning.",
  "ft_cleanup_per_fold": "If true, cleanup CUDA memory after each FT fold/trial.",
  "ft_cleanup_synchronize": "If true, synchronize CUDA before/after FT cleanup (safer but slower).",
  "ft_embedding_source_features": "Raw features considered as FT embedding source. null means use all feature_list columns.",
  "ft_feature_prefix": "Prefix used when exporting FT-generated feature columns.",
  "ft_num_numeric_tokens": "Optional number of numeric tokens in FT tokenizer (null = auto).",
  "ft_oof_folds": "Number of folds for FT out-of-fold feature generation (null = auto).",
  "ft_oof_shuffle": "If true, shuffle data for FT OOF random KFold strategy.",
  "ft_oof_strategy": "FT OOF split strategy. Allowed: auto, random, group, grouped, time, timeseries, temporal.",
  "ft_predict_batch_size": "Optional FT inference batch size (null = auto).",
  "ft_role": "FT execution role. Allowed: model, embedding, unsupervised_embedding. model and embedding roles run follow the hyperparameters specified in ft_search_space, while unsupervised_embedding runs with ft_unsupervised_search_space. The embedding role is intended for generating FT features without supervised fine-tuning, while the unsupervised_embedding role is intended for running FT in a self-supervised manner without any target/label input.",
  "ft_search_space": "Optuna search-space object for supervised FT hyperparameters.",
  "ft_search_space.d_model": "Search-space spec for FT (supervised) parameter 'd_model'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.dropout": "Search-space spec for FT (supervised) parameter 'dropout'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.geo_token_dropout": "Search-space spec for FT (supervised) parameter 'geo_token_dropout'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.geo_token_hidden_dim": "Search-space spec for FT (supervised) parameter 'geo_token_hidden_dim'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.geo_token_k_neighbors": "Search-space spec for FT (supervised) parameter 'geo_token_k_neighbors'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.geo_token_layers": "Search-space spec for FT (supervised) parameter 'geo_token_layers'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.geo_token_learning_rate": "Search-space spec for FT (supervised) parameter 'geo_token_learning_rate'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.learning_rate": "Search-space spec for FT (supervised) parameter 'learning_rate'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.n_layers": "Search-space spec for FT (supervised) parameter 'n_layers'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.tw_power": "Search-space spec for FT (supervised) parameter 'tw_power'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_search_space.weight_decay": "Search-space spec for FT (supervised) parameter 'weight_decay'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space": "Optuna search-space object for unsupervised FT pretraining hyperparameters.",
  "ft_unsupervised_search_space.cat_loss_weight": "Search-space spec for FT (unsupervised) parameter 'cat_loss_weight'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.d_model": "Search-space spec for FT (unsupervised) parameter 'd_model'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.dropout": "Search-space spec for FT (unsupervised) parameter 'dropout'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.learning_rate": "Search-space spec for FT (unsupervised) parameter 'learning_rate'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.mask_prob_cat": "Search-space spec for FT (unsupervised) parameter 'mask_prob_cat'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.mask_prob_num": "Search-space spec for FT (unsupervised) parameter 'mask_prob_num'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.n_layers": "Search-space spec for FT (unsupervised) parameter 'n_layers'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.num_loss_weight": "Search-space spec for FT (unsupervised) parameter 'num_loss_weight'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_unsupervised_search_space.weight_decay": "Search-space spec for FT (unsupervised) parameter 'weight_decay'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "ft_use_lazy_dataset": "If true, FT uses lazy row-wise dataset instead of full tensor materialization.",
  "geo_feature_nmes": "Raw feature names used to build geo-token inputs.",
  "geo_token_dropout": "Dropout used by geo-token network.",
  "geo_token_epochs": "Epochs for geo-token submodule training.",
  "geo_token_hidden_dim": "Hidden dimension for geo-token network.",
  "geo_token_k_neighbors": "Number of neighbors for geo-token KNN graph construction.",
  "geo_token_layers": "Number of layers in geo-token network.",
  "geo_token_learning_rate": "Learning rate for geo-token submodule training.",
  "gnn_approx_knn_threshold": "Row threshold above which approximate KNN is used.",
  "gnn_cleanup_per_fold": "If true, cleanup CUDA memory after each GNN fold/trial.",
  "gnn_cleanup_synchronize": "If true, synchronize CUDA before/after GNN cleanup (safer but slower).",
  "gnn_graph_cache": "Path to cached GNN graph artifact (null disables cache).",
  "gnn_knn_gpu_mem_overhead": "Safety multiplier used when estimating GPU memory for GNN KNN.",
  "gnn_knn_gpu_mem_ratio": "Fraction of free GPU memory budget for GNN KNN build (0,1].",
  "gnn_max_fit_rows": "Optional cap on rows used for GNN fit.",
  "gnn_max_gpu_knn_nodes": "Maximum nodes for GPU KNN build before fallback/chunking.",
  "gnn_max_predict_rows": "Optional cap on rows used for GNN prediction.",
  "gnn_predict_chunk_rows": "Prediction chunk size for GNN inference.",
  "gnn_use_approx_knn": "Enable approximate KNN graph build for large datasets.",
  "holdout_ratio": "Holdout test-set ratio for train/test split (0-1).",
  "infer_categorical_max_ratio": "Auto-categorical detection: max unique-ratio threshold.",
  "infer_categorical_max_unique": "Auto-categorical detection: max unique-count threshold.",
  "keep_unscaled_oht": "If true, retain an unscaled OHT copy in memory for reuse.",
  "loss_name": "Explicit loss override. Regression: auto/tweedie/poisson/gamma/mse/mae. Classification: auto/logloss/bce.",
  "model_categories": "Model category identifiers paired 1:1 with model_list.",
  "model_keys": "Generic model-key list used by plotting/prediction workflows. Typical keys: xgb, resn, ft, glm, gnn.",
  "model_labels": "Display labels for model keys used in plots/reports.",
  "model_labels.resn": "Display label for ResNet model in plots/reports.",
  "model_labels.xgb": "Display label for XGBoost model in plots/reports.",
  "model_list": "Primary model identifiers (paired 1:1 with model_categories).",
  "oht_sparse_csr": "If true, store one-hot matrix as sparse CSR where supported.",
  "optuna_cleanup_synchronize": "If true, synchronize CUDA during trial-level cleanup inside Optuna loop.",
  "optuna_storage": "Optuna storage DSN or local path (for example sqlite file) used to persist studies.",
  "optuna_study_prefix": "Prefix used when naming Optuna studies.",
  "output_dir": "Output directory for models, predictions, reports, and plots.",
  "plot": "Plotting options object.",
  "plot.double_lift": "If true, generate double-lift comparison plots.",
  "plot.double_lift_pairs": "Explicit model-key pairs for double-lift plots.",
  "plot.enable": "Master switch for plotting features.",
  "plot.lift_models": "Model keys used to draw lift curves.",
  "plot.n_bins": "Default number of bins for lift/one-way style plots.",
  "plot.oneway": "If true, generate one-way plots.",
  "plot.oneway_pred": "If true, include prediction-based one-way plots.",
  "plot.pre_oneway": "If true, run one-way plotting before model training.",
  "plot_curves": "If true, generate training loss curves.",
  "plot_path_style": "Plot directory layout. Allowed: nested, flat.",
  "prediction_cache_dir": "Directory used to save cached predictions.",
  "prediction_cache_format": "Prediction cache file format. Allowed: parquet, csv.",
  "preprocess_artifact_path": "Output path for saved preprocessing artifacts.",
  "prop_test": "Legacy validation ratio (kept for backward compatibility).",
  "psi_bins": "Number of bins used when computing PSI.",
  "psi_features": "Feature columns included in PSI drift report.",
  "psi_strategy": "PSI binning strategy. Typical values: quantile, uniform.",
  "rand_seed": "Global random seed for data split, CV, and reproducibility.",
  "region_city_col": "City column for region-effect feature engineering.",
  "region_effect_alpha": "Smoothing strength for region-effect feature.",
  "region_province_col": "Province column for region-effect feature engineering.",
  "register_model": "If true, register trained model metadata into model registry.",
  "registry_path": "Path to model registry storage file/database.",
  "registry_status": "Status assigned on registration (for example: candidate, approved, production).",
  "registry_tags": "Additional tags/metadata attached during model registration.",
  "report_group_cols": "Group-by columns for grouped validation metrics in reports.",
  "report_output_dir": "Directory where evaluation/report artifacts are written.",
  "report_time_ascending": "Sort order for time-trend output (true = oldest to newest).",
  "report_time_col": "Datetime column used to build time-trend reports.",
  "report_time_freq": "Time bucketing frequency for trend reports. Common values: D (day), W (week), M (month), Q (quarter), Y (year). Any pandas Period alias accepted.",
  "resn_cleanup_per_fold": "If true, cleanup CUDA memory after each ResNet fold/trial.",
  "resn_cleanup_synchronize": "If true, synchronize CUDA before/after ResNet cleanup (safer but slower).",
  "resn_predict_batch_size": "Optional ResNet inference batch size (null = auto).",
  "resn_search_space": "Optuna search-space object for ResNet hyperparameters.",
  "resn_search_space.block_num": "Search-space spec for ResNet parameter 'block_num'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_search_space.dropout": "Search-space spec for ResNet parameter 'dropout'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_search_space.hidden_dim": "Search-space spec for ResNet parameter 'hidden_dim'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_search_space.learning_rate": "Search-space spec for ResNet parameter 'learning_rate'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_search_space.patience": "Search-space spec for ResNet parameter 'patience'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_search_space.residual_scale": "Search-space spec for ResNet parameter 'residual_scale'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_search_space.stochastic_depth": "Search-space spec for ResNet parameter 'stochastic_depth'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_search_space.tw_power": "Search-space spec for ResNet parameter 'tw_power'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "resn_use_lazy_dataset": "If true, ResNet uses lazy row-wise dataset instead of full tensor materialization.",
  "resn_weight_decay": "Default weight decay for ResNet training.",
  "reuse_best_params": "If true, reuse saved best-parameter files instead of re-tuning.",
  "runner": "Runner control object used by config-driven CLI entrypoints.",
  "runner.explain_args": "Extra CLI arguments passed to explain mode runner.",
  "runner.ft_role": "Optional FT role override for runner execution.",
  "runner.idle_seconds": "Watchdog idle timeout in seconds.",
  "runner.incremental_args": "Extra CLI arguments passed to incremental mode runner.",
  "runner.max_evals": "Maximum Optuna trials per model.",
  "runner.max_restarts": "Maximum restart attempts by watchdog.",
  "runner.mode": "Runner mode. Allowed: entry, incremental, explain (watchdog is supported as alias in notebook utility).",
  "runner.model_keys": "Model keys to run in entry mode. Common keys: glm, xgb, resn, ft, gnn, all.",
  "runner.nproc_per_node": "Number of processes per node when launching torchrun/DDP.",
  "runner.plot_curves": "Override plot_curves during runner execution.",
  "runner.restart_delay_seconds": "Delay between watchdog restarts (seconds).",
  "runner.use_watchdog": "Wrap execution with watchdog auto-restart logic.",
  "save_preprocess": "If true, save preprocessing artifacts for later inference/reuse.",
  "split_cache_force_rebuild": "If true, ignore existing split cache and rebuild it.",
  "split_cache_path": "Path for persisted train/test split cache file.",
  "split_group_col": "Grouping column used when split_strategy is group.",
  "split_strategy": "Holdout split strategy. Typical values: random, group, time.",
  "split_time_ascending": "If true, time-based split keeps earlier rows in train and later rows in test.",
  "split_time_col": "Time column used when split_strategy is time.",
  "stack_model_keys": "Model keys trained after FT feature generation in stacked workflows.",
  "stream_split_chunksize": "Chunk size used when stream_split_csv is enabled.",
  "stream_split_csv": "If true, perform chunked/streaming CSV split to reduce peak memory.",
  "target": "Target column name.",
  "target_clip_enabled": "If true, clip training target by upper quantile before fitting.",
  "target_clip_quantile": "Upper quantile for target clipping when target_clip_enabled=true (0<q<=1).",
  "task_type": "Task type. Allowed: regression, classification.",
  "test_data_path": "Optional explicit test dataset path. Use together with train_data_path.",
  "threshold": "Threshold-optimization options object.",
  "threshold.enable": "Enable automatic threshold search.",
  "threshold.grid": "Number of candidate thresholds evaluated in grid search.",
  "threshold.max_rows": "Maximum rows used during threshold search.",
  "threshold.metric": "Optimization metric for threshold search (for example: f1, precision, recall, accuracy).",
  "threshold.min_positive_rate": "Lower bound on predicted positive rate during threshold search.",
  "threshold.seed": "Random seed for threshold sampling.",
  "threshold.value": "Fixed classification threshold. Set null to auto-search.",
  "train_data_path": "Optional explicit training dataset path. Use together with test_data_path.",
  "use_ft_data_parallel": "Enable DataParallel for FT model (single-process multi-GPU).",
  "use_ft_ddp": "Enable DistributedDataParallel (DDP) for FT.",
  "use_gnn_data_parallel": "Enable DataParallel for GNN model (single-process multi-GPU).",
  "use_gpu": "Enable GPU acceleration when available.",
  "use_resn_data_parallel": "Enable DataParallel for ResNet (single-process multi-GPU).",
  "use_resn_ddp": "Enable DistributedDataParallel (DDP) for ResNet.",
  "use_runtime_ft_embedding": "If true, recompute FT embeddings at runtime for downstream plotting/comparison workflows.",
  "val_ratio": "Validation ratio used inside model training when applicable (0-1).",
  "weight": "Sample-weight column name.",
  "xgb_cleanup_per_fold": "If true, cleanup CUDA memory after each XGBoost fold/trial.",
  "xgb_cleanup_synchronize": "If true, synchronize CUDA before/after XGBoost cleanup (safer but slower).",
  "xgb_gpu_id": "GPU device index used by XGBoost when GPU mode is enabled.",
  "xgb_max_depth_max": "Upper bound guard for XGBoost max_depth during tuning.",
  "xgb_n_estimators_max": "Upper bound guard for XGBoost n_estimators during tuning.",
  "xgb_search_space": "Optuna search-space object for XGBoost hyperparameters.",
  "xgb_search_space.gamma": "Search-space spec for XGBoost parameter 'gamma'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_search_space.learning_rate": "Search-space spec for XGBoost parameter 'learning_rate'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_search_space.max_depth": "Search-space spec for XGBoost parameter 'max_depth'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_search_space.min_child_weight": "Search-space spec for XGBoost parameter 'min_child_weight'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_search_space.n_estimators": "Search-space spec for XGBoost parameter 'n_estimators'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_search_space.reg_alpha": "Search-space spec for XGBoost parameter 'reg_alpha'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_search_space.reg_lambda": "Search-space spec for XGBoost parameter 'reg_lambda'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_search_space.tweedie_variance_power": "Search-space spec for XGBoost parameter 'tweedie_variance_power'. Use either a fixed value or an object with fields such as type/low/high/step/log/choices/value.",
  "xgb_use_dmatrix": "If true, use XGBoost DMatrix/QuantileDMatrix training path."
}
